{{- if .Values.redisInCluster.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "genus-os.fullname" . }}-redis
  labels:
    {{- include "genus-os.labels" (dict "root" . "component" "redis") | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: redis
      port: {{ .Values.redisInCluster.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "genus-os.selectorLabels" (dict "root" . "component" "redis") | nindent 4 }}
{{- end }}
