import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { render } from "@testing-library/react";

const mockVisual = vi.hoisted(() => ({
  pendingAgentData: null as Record<string, unknown> | null,
}));

vi.mock("@/hooks/use-visual-state", () => ({
  useVisualState: () => ({
    currentView: null,
    viewStack: [],
    popView: vi.fn(),
    clearViews: vi.fn(),
    canvasMode: "idle",
    setCanvasMode: vi.fn(),
    dashboardCode: null,
    setDashboardCode: vi.fn(),
    clearDashboard: vi.fn(),
    isUpdating: false,
    pendingAgentData: mockVisual.pendingAgentData,
  }),
}));
vi.mock("@/hooks/use-dashboard-agent", () => ({ useDashboardAgent: vi.fn() }));
vi.mock("@/lib/dashboard/error-reporter", () => ({ reportDashboardError: vi.fn() }));

describe("LiveCanvas — first load", () => {
  let fetchMock: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    mockVisual.pendingAgentData = null;
    fetchMock = vi.fn().mockResolvedValue(new Response("{}", { status: 404 }));
    vi.stubGlobal("fetch", fetchMock);
  });

  afterEach(() => {
    vi.unstubAllGlobals();
  });

  const welcomeCalls = () =>
    fetchMock.mock.calls.filter(([url]) =>
      ["/api/session", "/api/dashboard/welcome"].includes(String(url)),
    );

  async function renderCanvas() {
    const { LiveCanvas } = await import("../live-canvas");
    return render(<LiveCanvas />);
  }

  it("loads the welcome view when nothing was asked for", async () => {
    await renderCanvas();
    expect(welcomeCalls().length).toBeGreaterThan(0);
  });

  it("does not load a welcome view over a visual the agent asked for", async () => {
    // The agent's [DASHBOARD:…] data is about to be generated by the
    // dashboard agent; a welcome page arriving later would overwrite it.
    mockVisual.pendingAgentData = { intent: "bar_chart" };
    await renderCanvas();
    expect(welcomeCalls()).toHaveLength(0);
  });
});
