"""Give each paired peer a broker account, or pairing ends at a wall.

`render_config` and `PeerAccount` existed, were tested, and had no production
caller — only the soak, which built its account config by hand. So
`robothor federation invite` minted a token, persisted a row, and provisioned
nothing: the peer would redeem the token, do everything right, and be refused
by the broker with an Authorization Violation.

That is the same shape as `set_nats_manager`, which also had no production
caller and left this instance unable to make an outbound federation call for
five months without logging a single error. `test_wiring.py` now covers this
one too.
"""

from __future__ import annotations

import logging
import os
import secrets
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any

from robothor.federation.models import Connection, ConnectionState
from robothor.federation.nats_config import PeerAccount, render_accounts_block

if TYPE_CHECKING:
    from collections.abc import Sequence

logger = logging.getLogger(__name__)

#: Where the broker's main config lives. The unit points at this path, and it
#: was untracked until 2026-08-27 — a rebuild from the repo produced a service
#: whose config file nothing in the repo created.
DEFAULT_MAIN_CONFIG = Path(os.environ.get("ROBOTHOR_NATS_CONFIG", "/etc/nats/nats-server.conf"))

#: The drop-in, regenerated whole on every change.
ACCOUNTS_FILENAME = "federation.d/accounts.conf"

#: States whose peer may hold a live broker account. PENDING is included
#: deliberately: the peer has to connect in order to complete the handshake
#: that activates it, so provisioning only ACTIVE connections would deadlock
#: every pairing. SUSPENDED is excluded just as deliberately — a kill switch
#: that leaves the credential working is not one.
_PROVISIONED_STATES = frozenset({ConnectionState.ACTIVE, ConnectionState.PENDING})


@dataclass
class Provisioned:
    accounts_path: Path
    peers: list[PeerAccount]
    include_line: str


def peer_credentials(connection: Connection) -> dict[str, str]:
    """The credential this peer presents, minting one on first use.

    Stored on the connection so regenerating the config never rotates a live
    peer's password out from under it — every other connection would keep
    working and that one would start failing authorization for no visible
    reason.
    """
    transport = connection.transport or {}
    account = PeerAccount(
        connection.id,
        password=str(transport.get("password") or secrets.token_urlsafe(24)),
    )
    connection.transport = {
        **transport,
        "kind": "nats",
        "user": account.user,
        "password": account.password,
        "account": account.account,
    }
    return {"user": account.user, "password": account.password}


def provision_broker(
    connections: Sequence[Connection],
    *,
    main_config: Path | None = None,
    engine_password: str = "",
) -> Provisioned:
    """Write the accounts drop-in for every peer entitled to one.

    Does NOT reload the broker — the caller decides when, and has to be able to
    report a failed reload. A config nats-server has not read is a config that
    does nothing.
    """
    main = Path(main_config) if main_config else DEFAULT_MAIN_CONFIG
    accounts_path = main.parent / ACCOUNTS_FILENAME
    accounts_path.parent.mkdir(parents=True, exist_ok=True)

    peers = [
        PeerAccount(c.id, password=peer_credentials(c)["password"])
        for c in connections
        if c.state in _PROVISIONED_STATES
    ]

    engine_password = engine_password or os.environ.get("ROBOTHOR_NATS_PASSWORD", "")
    accounts_path.write_text(render_accounts_block(engine_password=engine_password, peers=peers))
    # Every peer's password in plaintext, which is what nats-server requires.
    # Nothing else on the box should be able to read it.
    accounts_path.chmod(0o600)

    include_line = f'include "{ACCOUNTS_FILENAME}"'
    _ensure_include(main, include_line)

    logger.info("Federation: provisioned %d broker account(s) in %s", len(peers), accounts_path)
    return Provisioned(accounts_path=accounts_path, peers=peers, include_line=include_line)


def _ensure_include(main: Path, include_line: str) -> None:
    """Append the include once. A second invite must not duplicate it."""
    try:
        text = main.read_text()
    except OSError:
        logger.warning("Federation: could not read %s to add the accounts include", main)
        return
    if ACCOUNTS_FILENAME in text:
        return
    with main.open("a") as handle:
        handle.write("\n# Per-connection accounts, generated by `robothor federation invite`.\n")
        handle.write(f"{include_line}\n")


def _run(argv: list[str]) -> tuple[int, str]:
    try:
        done = subprocess.run(argv, capture_output=True, text=True, timeout=30)
        return done.returncode, (done.stderr or done.stdout or "").strip()
    except Exception as exc:  # noqa: BLE001
        return 1, str(exc)


def reload_broker(unit: str = "robothor-nats") -> tuple[bool, str]:
    """Ask nats-server to re-read its config. Returns (ok, detail).

    Never raises: a failed reload is something the CLI must be able to REPORT,
    because the operator has just handed out a token that will not work until
    the broker has read the account.
    """
    code, detail = _run(["systemctl", "reload", unit])
    if code == 0:
        return True, "broker reloaded"
    code, detail2 = _run(["sudo", "-n", "systemctl", "reload", unit])
    if code == 0:
        return True, "broker reloaded"
    return False, (
        f"could not reload {unit}: {detail or detail2}. The account exists on "
        f"disk but nats-server has not read it, so the peer will be refused. "
        f"Run: sudo systemctl reload {unit}"
    )


def provision_and_reload(
    connections: Sequence[Connection], **kwargs: Any
) -> tuple[Provisioned, bool, str]:
    result = provision_broker(connections, **kwargs)
    ok, detail = reload_broker()
    return result, ok, detail
