"""``genus init`` — the command, and the pieces of it the wizard borrows.

This module is the ORCHESTRATOR. It turns flags and the environment into an
:class:`robothor.init.context.InitContext`, asks the chosen substrate for its
plan, runs the two phases and owns the exit code. Every decision the wizard
makes lives in :mod:`robothor.init`.

It also keeps the handful of helpers that predate the package and are still
the single implementation of what they do -- ``create_workspace``,
``check_prerequisites``, the ``.robothor/init_state.yaml`` reader and writer,
the Ollama puller, the Docker infrastructure generator -- because the steps
call them, and two copies of "create a workspace" is how a scaffold silently
stops shipping half its files.

Usage:
    genus init                     # interactive
    genus init --yes               # non-interactive; defaults and environment
    genus init --yes --json        # one document on stdout, humans on stderr
    genus init --dry-run           # print the plan, write nothing
"""

from __future__ import annotations

import json
import os
import platform
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import TYPE_CHECKING, Any

import httpx
import yaml

from robothor.config import DatabaseConfig, OllamaConfig, RedisConfig

if TYPE_CHECKING:  # pragma: no cover - typing only
    from collections.abc import Sequence

# Models required for the RAG pipeline
REQUIRED_MODELS = ["qwen3-embedding:0.6b", "Qwen3-Reranker-0.6B:F16"]

DOCKER_COMPOSE_TEMPLATE = """\
# Generated by: robothor init --docker
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: robothor-postgres
    restart: always
    environment:
      POSTGRES_DB: robothor_memory
      POSTGRES_USER: robothor
      POSTGRES_PASSWORD: "{db_password}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U robothor -d robothor_memory"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: robothor-redis
    restart: always
    command: redis-server --maxmemory 2gb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: robothor-ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      OLLAMA_HOST: "0.0.0.0"

volumes:
  postgres_data:
  redis_data:
  ollama_data:
"""


def _save_init_state(workspace: Path, step: str, status: str) -> None:
    """Write init progress to .robothor/init_state.yaml for resume support."""
    state_dir = workspace / ".robothor"
    state_dir.mkdir(parents=True, exist_ok=True)
    state_path = state_dir / "init_state.yaml"

    state: dict[str, Any] = {}
    if state_path.exists():
        state = yaml.safe_load(state_path.read_text()) or {}
    state[step] = status

    state_path.write_text(yaml.dump(state, default_flow_style=False))


def _load_init_state(workspace: Path) -> dict[str, str]:
    """Load init progress from .robothor/init_state.yaml."""
    state_path = workspace / ".robothor" / "init_state.yaml"
    if not state_path.exists():
        return {}
    return yaml.safe_load(state_path.read_text()) or {}


#: Answers ``--yes`` takes from the environment when no flag supplies them.
#: ``ROBOTHOR_OWNER_NAME``/``ROBOTHOR_OWNER_EMAIL`` are deprecated as runtime
#: configuration -- owner.yaml is the identity -- but they are still how a
#: provisioning script tells a non-interactive install WHO the operator is, and
#: nothing else can: there is no terminal to ask.
_ANSWER_ENV = {
    "owner_name": "ROBOTHOR_OWNER_NAME",
    "owner_email": "ROBOTHOR_OWNER_EMAIL",
    "ai_name": "ROBOTHOR_AI_NAME",
    "ai_email": "ROBOTHOR_AI_EMAIL",
    "tenant_id": "ROBOTHOR_DEFAULT_TENANT",
    "telegram_token": "ROBOTHOR_TELEGRAM_BOT_TOKEN",
}

#: Answers taken from flags, as {answer key: argparse attribute}.
_ANSWER_FLAGS = {
    "preset": "preset",
    "provider_id": "provider",
    "provider_model": "model",
    "secrets_backend": "secrets_backend",
    "telegram_token": "telegram_token",
    "owner_name": "owner_name",
    "owner_email": "owner_email",
    "skip_models": "skip_models",
    "skip_db": "skip_db",
    "docker": "docker",
    "start": "start",
}


def _provider_key_from_env() -> str:
    """The credential for the provider whose key this box already carries.

    Read straight from the process environment rather than through the settings
    model on purpose: provider keys are secrets, they are not settings, and the
    only thing this value is ever used for is one probe call.
    """
    from robothor.engine.key_pool import PROVIDERS

    for spec in PROVIDERS:
        value = os.environ.get(spec.env_var, "").strip()
        if value:
            return value
    return ""


def build_init_context(args: Any) -> Any:
    """Turn parsed flags and the environment into an :class:`InitContext`.

    Every answer the wizard could need is seeded here, which is what lets
    ``--yes`` run without a terminal: ``ctx.ask`` only prompts for what it was
    not given.
    """
    from robothor.init.context import InitContext

    workspace = Path(getattr(args, "workspace", None) or Path.home() / "robothor")

    answers: dict[str, Any] = {}
    for key, attribute in _ANSWER_FLAGS.items():
        value = getattr(args, attribute, None)
        if value not in (None, "", False):
            answers[key] = value
    for key, variable in _ANSWER_ENV.items():
        if key in answers:
            continue
        value = os.environ.get(variable, "").strip()
        if value:
            answers[key] = value
    key = _provider_key_from_env()
    if key:
        answers["provider_key"] = key

    return InitContext(
        workspace=workspace,
        answers=answers,
        dry_run=bool(getattr(args, "dry_run", False)),
        json_mode=bool(getattr(args, "json", False)),
        yes=bool(getattr(args, "yes", False)),
        offline=bool(getattr(args, "offline", False)),
        substrate_name=str(
            getattr(args, "substrate", None) or os.environ.get("ROBOTHOR_INIT_SUBSTRATE") or "local"
        ),
    )


def run_init(args: Any) -> int:
    """Two-phase orchestrator for the first-run wizard.

    Phase 1 checks everything and prints the plan. Phase 2 applies it, one
    resumable step at a time. The steps themselves live in ``robothor.init``;
    this function owns the flags, the streams and the exit code, and nothing
    else -- which is why ``genus init --json`` can put one document on stdout
    without a single step knowing about it.
    """
    from robothor.init.plan import run_plan
    from robothor.init.render import (
        render_json,
        render_outcome,
        render_plan,
        render_summary,
    )
    from robothor.init.substrate import build_plan

    ctx = build_init_context(args)
    ctx.say("")
    ctx.say("  Genus OS Setup")
    ctx.say("  " + "=" * 14)
    ctx.say("")

    try:
        plan = build_plan(ctx)
    except (NotImplementedError, ValueError) as exc:
        # A substrate that is designed but not built, or one that does not
        # exist. Both are the operator's command, not the operator's machine,
        # so neither is a plan row -- there is no plan to put it in.
        ctx.say(f"  --substrate {ctx.substrate_name}: {exc}")
        return 1

    width = max((len(step.id) for step in plan.steps), default=0)
    applying = False

    def show_plan(entries: Any) -> None:
        nonlocal applying
        for line in render_plan(entries, plan.substrate_name):
            ctx.say(line)
        if not any(row.status == "blocked" for row in entries):
            ctx.say("")
            ctx.say("  Dry run:" if ctx.dry_run else "  Applying:")
            applying = True

    def show_step(outcome: Any) -> None:
        if applying:
            ctx.say(render_outcome(outcome, width))

    result = run_plan(ctx, plan, on_plan=show_plan, on_step=show_step)

    for line in render_summary(result, workspace=str(ctx.workspace)):
        ctx.say(line)
    if getattr(args, "json", False):
        print(render_json(result))
    return int(result.exit_code)


def check_prerequisites(
    *,
    docker_required: bool = False,
    required: Sequence[str] = (),
) -> list[dict[str, Any]]:
    """Check for required and optional tools.

    Returns a list of dicts: {name, found, detail, required, hint}.

    ``required`` names the tools THIS substrate cannot run without, by the
    ``name`` field below. Every prerequisite used to be optional on every
    install, which is why a box with no PostgreSQL passed this check and then
    failed at the migration, four steps and one operator identity later.
    Python stays required unconditionally; nothing runs without it.
    """
    wanted = set(required)

    def _required(name: str, *, always: bool = False) -> bool:
        return always or name in wanted

    results = []

    # Python (always present)
    results.append(
        {
            "name": "Python",
            "found": True,
            "detail": f"{sys.version.split()[0]}",
            "required": True,
            "hint": "",
        }
    )

    # psql
    psql = shutil.which("psql")
    results.append(
        {
            "name": "PostgreSQL (psql)",
            "found": psql is not None,
            "detail": "found" if psql else "not found",
            "required": _required("PostgreSQL (psql)"),
            "hint": _install_hint("postgresql-client", "postgresql"),
        }
    )

    # redis-cli
    redis_cli = shutil.which("redis-cli")
    results.append(
        {
            "name": "Redis (redis-cli)",
            "found": redis_cli is not None,
            "detail": "found" if redis_cli else "not found",
            "required": _required("Redis (redis-cli)"),
            "hint": _install_hint("redis-server", "redis"),
        }
    )

    # Ollama
    ollama_found = False
    ollama_detail = "not reachable"
    try:
        base_url = os.environ.get("ROBOTHOR_OLLAMA_HOST", "127.0.0.1")
        port = os.environ.get("ROBOTHOR_OLLAMA_PORT", "11434")
        resp = httpx.get(f"http://{base_url}:{port}/api/tags", timeout=3)
        resp.raise_for_status()
        models = resp.json().get("models", [])
        ollama_found = True
        ollama_detail = f"{len(models)} model(s) loaded"
    except Exception:
        ollama_detail = "not reachable"
    results.append(
        {
            "name": "Ollama",
            "found": ollama_found,
            "detail": ollama_detail,
            "required": _required("Ollama"),
            "hint": "curl -fsSL https://ollama.com/install.sh | sh",
        }
    )

    # Docker (required only with --docker)
    docker_bin = shutil.which("docker")
    results.append(
        {
            "name": "Docker",
            "found": docker_bin is not None,
            "detail": "found" if docker_bin else "not found",
            "required": _required("Docker", always=docker_required),
            "hint": "https://docs.docker.com/engine/install/",
        }
    )

    return results


def setup_vault_key(workspace: Path) -> Path:
    """Generate vault master key if it doesn't exist."""
    from robothor.vault.crypto import init_master_key

    return init_master_key(workspace)


# Scaffold files create_workspace() copies out of the template dir, as
# {source name in templates/: destination relative to the workspace}. This is
# the expected-files manifest — robothor/tests/test_template_resolution.py
# checks every source name against the real templates/ listing, so a rename
# in the scaffold fails the build instead of silently scaffolding less.
BRAIN_SCAFFOLD_FILES = {
    "SOUL.md": "SOUL.md",
    "IDENTITY.md": "IDENTITY.md",
    "AGENTS.md": "AGENTS.md",
    "TOOLS.md": "TOOLS.md",
    "HEARTBEAT.md": "HEARTBEAT.md",
    "USER.md": "USER.md",
    "BOOTSTRAP.md": "BOOTSTRAP.md",
    "brain-CLAUDE.md": "CLAUDE.md",
}
DOCS_SCAFFOLD_FILES = ("agent-manifest.yaml", "agent-instructions.md")
ROOT_SCAFFOLD_FILES = ("CLAUDE.md", "AGENT_BUILDER.md", "ONBOARDING.md")
EXPECTED_SCAFFOLD_FILES: tuple[str, ...] = (
    *BRAIN_SCAFFOLD_FILES,
    *DOCS_SCAFFOLD_FILES,
    *ROOT_SCAFFOLD_FILES,
)


def _copy_scaffold_file(template_dir: Path, src_name: str, dst: Path) -> None:
    """Copy one scaffold file, warning (not silently skipping) when absent."""
    src = template_dir / src_name
    if not src.exists():
        print(f"  Warning: scaffold template {src_name} missing from {template_dir} — skipped")
        return
    if not dst.exists():
        dst.write_text(src.read_text())


def create_workspace(path: Path) -> None:
    """Create workspace directory structure with brain/ scaffold from templates."""
    path.mkdir(parents=True, exist_ok=True)
    (path / "memory").mkdir(exist_ok=True)
    (path / "faces").mkdir(exist_ok=True)

    # Brain directory — identity, runtime state, agent instructions
    brain = path / "brain"
    brain.mkdir(exist_ok=True)
    (brain / "memory").mkdir(exist_ok=True)

    # Docs directories — agent manifests and workflows
    docs = path / "docs"
    (docs / "agents").mkdir(parents=True, exist_ok=True)
    (docs / "workflows").mkdir(parents=True, exist_ok=True)

    # Copy template files into brain/ (never overwrite existing)
    template_dir = _find_template_dir()
    if template_dir is None:
        print(
            "  Warning: no scaffold templates found (checked ROBOTHOR_TEMPLATE_DIR, "
            "repo-root templates/, and the bundled package data) — "
            "workspace created without scaffold files"
        )
    else:
        for src_name, dst_name in BRAIN_SCAFFOLD_FILES.items():
            _copy_scaffold_file(template_dir, src_name, brain / dst_name)

        # Copy agent manifest template to docs/agents/
        for name in DOCS_SCAFFOLD_FILES:
            _copy_scaffold_file(template_dir, name, docs / "agents" / name)

        # Copy CLAUDE.md files to workspace root
        for fname in ROOT_SCAFFOLD_FILES:
            _copy_scaffold_file(template_dir, fname, path / fname)

        # Snapshot template hashes so `robothor upgrade` can detect changes.
        #
        # Written to `path`, explicitly. `_save_state()` resolves its own
        # location from ROBOTHOR_WORKSPACE or ~/robothor, so a scaffold created
        # at X used to drop this file into Y — and Y is somebody's live
        # instance whenever X came from `--workspace`.
        from robothor.cli.upgrade import _snapshot_template_hashes

        state_data: dict[str, Any] = {}
        state_file = path / ".robothor" / "migrations_applied.yaml"
        if state_file.exists():
            state_data = yaml.safe_load(state_file.read_text()) or {}
        state_data["template_hashes"] = _snapshot_template_hashes()
        state_file.parent.mkdir(parents=True, exist_ok=True)
        state_file.write_text(yaml.dump(state_data, default_flow_style=False))


#: Scaffold files that carry ``{{...}}`` placeholders the wizard fills in.
TEMPLATED_FILES: tuple[str, ...] = (
    "CLAUDE.md",
    "AGENT_BUILDER.md",
    "brain/CLAUDE.md",
    "brain/SOUL.md",
    "brain/IDENTITY.md",
    "brain/USER.md",
)


def resolve_workspace_templates(
    workspace: Path,
    *,
    ai_name: str = "",
    ai_email: str = "",
    owner_name: str = "",
    owner_email: str = "",
) -> list[Path]:
    """Replace the scaffold's ``{{placeholders}}``. Returns what it rewrote.

    Extracted from the old ``run_init`` body so the wizard's workspace step can
    call it and a test can assert on it. Idempotent: a file with no ``{{`` left
    in it is not rewritten, so a re-run cannot undo an operator's edits.
    """
    replacements = {
        "{{ai_name}}": ai_name,
        "{{owner_name}}": owner_name,
        "{{ai_email}}": ai_email,
        "{{owner_email}}": owner_email,
    }
    rewritten: list[Path] = []
    for relative in TEMPLATED_FILES:
        path = workspace / relative
        if not path.exists():
            continue
        content = path.read_text()
        if "{{" not in content:
            continue
        for token, value in replacements.items():
            content = content.replace(token, value)
        path.write_text(content)
        rewritten.append(path)
    return rewritten


def write_workspace_pointer(workspace: Path) -> Path | None:
    """Write the one value ``config.yaml`` structurally cannot hold.

    ``.robothor/config.yaml`` lives INSIDE the workspace, so it cannot tell a
    process where the workspace is; that has to come from the environment. This
    writes a two-line ``.env`` carrying ``ROBOTHOR_WORKSPACE`` and nothing else,
    for anything that sources it.

    Everything else the old sixteen-line ``.env`` held -- the database, Redis,
    Ollama, the AI name, the timezone -- is now written through the settings
    writer into ``config.yaml``, by the step that owns it. Holding a value in
    two files means a later ``genus config set`` changes one of them, the
    environment silently wins, and the command reports "applied" while the
    service reads the old number.

    Never overwrites: an operator who has edited this file keeps their edit.
    Returns the path when it wrote one, else None.
    """
    path = workspace / ".env"
    if path.exists():
        return None
    path.write_text(
        "# Written by `genus init`. Everything else this instance configures\n"
        "# lives in .robothor/config.yaml -- `genus config get|set` reads and\n"
        "# writes it. This file carries only the pointer to the workspace,\n"
        "# which config.yaml cannot hold because it lives inside it.\n"
        f"ROBOTHOR_WORKSPACE={workspace}\n",
        encoding="utf-8",
    )
    return path


def _find_template_dir(package_dir: Path | None = None) -> Path | None:
    """Locate the init scaffold templates/ directory.

    Resolution order:

    1. ``ROBOTHOR_TEMPLATE_DIR`` — explicit operator override. When set it is
       authoritative: a bad value returns ``None`` rather than silently
       falling back to a different scaffold.
    2. Repo-root ``templates/`` when running from a checkout. Detected by
       walking the package directory's ancestors for a repo marker
       (``pyproject.toml`` + ``templates/`` + the ``robothor`` package), not
       by parent-count arithmetic.
    3. The scaffold bundled into the wheel at
       ``robothor/templates/bundled_scaffold`` (see the force-include in
       pyproject.toml).

    The bare code-package dir (``robothor/templates/`` itself) is never
    returned — it contains Python modules, not the scaffold.
    """
    env_dir = os.environ.get("ROBOTHOR_TEMPLATE_DIR")
    if env_dir:
        env_path = Path(env_dir)
        if env_path.is_dir():
            return env_path
        print(f"  Warning: ROBOTHOR_TEMPLATE_DIR={env_dir} is not a directory")
        return None

    if package_dir is None:
        package_dir = Path(__file__).resolve().parent
    else:
        package_dir = package_dir.resolve()

    # Checkout layout: the repo root is the ancestor that has the project
    # marker files. Covers both `/repo/robothor/` and a venv nested inside
    # the repo (`/repo/venv/.../site-packages/robothor/`).
    for ancestor in package_dir.parents:
        if (
            (ancestor / "pyproject.toml").is_file()
            and (ancestor / "templates").is_dir()
            and (ancestor / "robothor" / "__init__.py").is_file()
        ):
            return ancestor / "templates"

    # Wheel layout: the scaffold ships as package data.
    bundled = package_dir / "templates" / "bundled_scaffold"
    if bundled.is_dir():
        return bundled
    if package_dir == Path(__file__).resolve().parent:
        # Fall back to importlib.resources for exotic install layouts.
        try:
            from importlib import resources

            resource_dir = Path(str(resources.files("robothor"))) / "templates"
            bundled = resource_dir / "bundled_scaffold"
            if bundled.is_dir():
                return bundled
        except Exception:  # pragma: no cover - defensive
            pass
    return None


def _detect_install_mode() -> str:
    """Return ``"checkout"`` or ``"wheel"`` for the running install.

    Reuses ``_find_template_dir()`` (the #245 scaffold-resolution helper)
    rather than re-deriving the checkout/wheel distinction: a checkout
    resolves to the repo-root ``templates/`` directory, a wheel install
    resolves to the bundled ``.../robothor/templates/bundled_scaffold``. If
    neither can be resolved, default to "wheel" — the more conservative
    guidance (no systemd assumptions).
    """
    template_dir = _find_template_dir()
    if template_dir is not None and template_dir.name != "bundled_scaffold":
        return "checkout"
    return "wheel"


def helm_port() -> int:
    """The port the Helm dashboard serves the wizard on.

    Read from the settings model so an instance that moved the dashboard gets a
    link that works. A config.yaml that does not parse falls back to the
    declared default rather than stopping init: this is the command an operator
    runs to fix such a box.
    """
    try:
        from robothor.settings import get_settings

        return int(get_settings().services.helm_port)
    except Exception:  # noqa: BLE001 - a broken config must not block first run
        return 3004


def pull_ollama_models(base_url: str, models: list[str]) -> None:
    """Pull required Ollama models with progress output."""
    for model in models:
        print(f"  Pulling {model} ...", end=" ", flush=True)
        try:
            with httpx.stream(
                "POST",
                f"{base_url}/api/pull",
                json={"name": model},
                timeout=httpx.Timeout(5.0, read=600.0),
            ) as resp:
                resp.raise_for_status()
                last_status = ""
                for line in resp.iter_lines():
                    if not line:
                        continue
                    try:
                        data = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    status = data.get("status", "")
                    if status != last_status:
                        last_status = status
                print("done")
        except Exception as e:
            print(f"failed ({e})")


def write_env_file(
    path: Path,
    db: DatabaseConfig,
    redis: RedisConfig,
    ollama: OllamaConfig,
    *,
    owner_name: str = "",
    ai_name: str = "Robothor",
    owner_email: str = "",
    ai_email: str = "",
    timezone: str = "America/New_York",
    profiles: list[str] | None = None,
    yes: bool = False,
) -> bool:
    """Write .env file with configuration. Returns True if written."""
    if path.exists() and not yes:
        overwrite = input(f"  {path} exists. Overwrite? [y/N]: ").strip().lower()
        if overwrite != "y":
            print(f"  Keeping existing {path}")
            return False

    # Extract non-secret config values — secrets are NEVER written to .env
    db_host = str(db.host)
    db_port = str(db.port)
    db_name = str(db.name)
    db_user = str(db.user)
    # Operator identity is NOT written here: ROBOTHOR_OWNER_NAME and
    # ROBOTHOR_OWNER_EMAIL are deprecated in favour of ~/.robothor/owner.yaml,
    # which run_init writes through robothor.owner_config.write_owner_config.
    # Two files claiming the same identity is how an instance ends up
    # answering to one name and filing CRM rows under another.
    lines = [
        f"ROBOTHOR_AI_NAME={ai_name}",
        f"ROBOTHOR_AI_EMAIL={ai_email}",
        f"ROBOTHOR_TIMEZONE={timezone}",
        f"ROBOTHOR_DB_HOST={db_host}",
        f"ROBOTHOR_DB_PORT={db_port}",
        f"ROBOTHOR_DB_NAME={db_name}",
        f"ROBOTHOR_DB_USER={db_user}",
        "# ROBOTHOR_DB_PASSWORD — set via SOPS secrets or env, not stored here",
        "ROBOTHOR_DB_PASSWORD=",
        f"ROBOTHOR_REDIS_HOST={redis.host}",
        f"ROBOTHOR_REDIS_PORT={redis.port}",
        f"ROBOTHOR_OLLAMA_HOST={ollama.host}",
        f"ROBOTHOR_OLLAMA_PORT={ollama.port}",
        f"ROBOTHOR_WORKSPACE={path.parent}",
    ]
    if profiles:
        lines.append(f"COMPOSE_PROFILES={','.join(profiles)}")
    path.write_text("\n".join(lines) + "\n")
    return True


def generate_docker_compose(workspace: Path, db_password: str) -> Path:
    """Generate a docker-compose.yml in the workspace directory."""
    compose_path = workspace / "docker-compose.yml"
    content = DOCKER_COMPOSE_TEMPLATE.format(db_password=db_password)
    compose_path.write_text(content)
    return compose_path


def wait_for_services(workspace: Path, timeout: int = 60) -> bool:
    """Start Docker containers and wait for health checks."""
    compose_file = workspace / "docker-compose.yml"
    if not compose_file.exists():
        return False

    result = subprocess.run(
        ["docker", "compose", "-f", str(compose_file), "up", "-d"],
        capture_output=True,
        text=True,
        cwd=str(workspace),
    )
    if result.returncode != 0:
        print(f"\n  Docker error: {result.stderr.strip()}")
        return False

    # Poll for PG readiness
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        try:
            import psycopg2  # type: ignore[import-untyped]

            conn = psycopg2.connect(
                host="127.0.0.1",
                port=5432,
                dbname="robothor_memory",
                user="robothor",
                password="robothor",
                connect_timeout=2,
            )
            conn.close()
            return True
        except Exception:
            time.sleep(2)

    return False


# --- Private helpers ---


def _db_config_from_env() -> DatabaseConfig:
    """Build DatabaseConfig from environment variables."""
    return DatabaseConfig(
        host=os.environ.get("ROBOTHOR_DB_HOST", "127.0.0.1"),
        port=int(os.environ.get("ROBOTHOR_DB_PORT", "5432")),
        name=os.environ.get("ROBOTHOR_DB_NAME", "robothor_memory"),
        user=os.environ.get("ROBOTHOR_DB_USER", os.environ.get("USER", "robothor")),
        password=os.environ.get("ROBOTHOR_DB_PASSWORD", ""),
    )


def _redis_config_from_env() -> RedisConfig:
    """Build RedisConfig from environment variables."""
    return RedisConfig(
        host=os.environ.get("ROBOTHOR_REDIS_HOST", "127.0.0.1"),
        port=int(os.environ.get("ROBOTHOR_REDIS_PORT", "6379")),
        db=int(os.environ.get("ROBOTHOR_REDIS_DB", "0")),
        password=os.environ.get("ROBOTHOR_REDIS_PASSWORD", ""),
    )


def _ollama_config_from_env() -> OllamaConfig:
    """Build OllamaConfig from environment variables."""
    return OllamaConfig(
        host=os.environ.get("ROBOTHOR_OLLAMA_HOST", "127.0.0.1"),
        port=int(os.environ.get("ROBOTHOR_OLLAMA_PORT", "11434")),
    )


def _install_hint(apt_pkg: str, brew_pkg: str) -> str:
    """Return platform-appropriate install hint."""
    if platform.system() == "Darwin":
        return f"brew install {brew_pkg}"
    return f"apt install {apt_pkg}  OR  brew install {brew_pkg}"


def _print_prerequisites(prereqs: list[dict[str, Any]]) -> None:
    """Print formatted prerequisite check results."""
    for p in prereqs:
        mark = "+" if p["found"] else "x"
        line = f"    {mark} {p['name']}"
        if p["found"]:
            line += f" ({p['detail']})"
        print(line)
        if not p["found"] and p["hint"]:
            print(f"      -> {p['hint']}")
