"""The instance env file, and the two rules for reading it.

``genus init --substrate compose`` writes every credential an instance has into
one 0600 file in its workspace, and the containers read it through compose's
``env_file``. The HOST needs the same values: ``genus doctor`` and the wizard's
own ``verify`` step resolve the database connection from the process
environment, and on a compose install the password was GENERATED by the wizard
and stored nowhere else. Without this module the doctor reported ``db.connect``
failing against a database that was running perfectly well, the wizard's last
step failed the install it had just completed, and the documented workaround
was a ``set -a; . ./genus.env`` line in the quickstart that an install gate
could silently drop.

**A file anyone else can read is refused, not loaded.** It carries the database
password and the provider key. Permissions that have slipped are a finding;
reading the file anyway would hide that finding forever, and the refusal names
the file, its mode and the one command that fixes it. A symlink at that path is
refused for the same reason — it is the shape of "make the daemon read a file
it would not otherwise open".

**An exported value always wins.** The load is ``setdefault``: an operator who
exported ``ROBOTHOR_DB_PASSWORD`` before running the command meant it, and a
file that overrode the environment would make an override impossible to debug.

Nothing here logs a value. Names, yes; values never.
"""

from __future__ import annotations

import stat
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:  # pragma: no cover - typing only
    from collections.abc import MutableMapping

__all__ = [
    "INSTANCE_ENV_FILENAME",
    "REQUIRED_MODE",
    "EnvFileLoad",
    "load_instance_env",
    "parse_env_file",
]

#: What ``genus init --substrate compose`` writes, in the workspace root.
INSTANCE_ENV_FILENAME = "genus.env"

#: The only mode this file may have. Anything wider is refused.
REQUIRED_MODE = 0o600


@dataclass(frozen=True)
class EnvFileLoad:
    """What one attempt to read the instance env file did.

    ``refused`` is a sentence for the operator, empty when there was nothing to
    refuse. A caller prints it; nothing here does, because this runs inside
    ``--json`` commands whose stdout is a contract.
    """

    path: Path
    present: bool = False
    names: tuple[str, ...] = field(default_factory=tuple)
    refused: str = ""

    @property
    def loaded(self) -> bool:
        """Whether anything was actually added to the environment."""
        return bool(self.names)


def parse_env_file(text: str) -> dict[str, str]:
    """``NAME=value`` pairs, with the quoting ``genus init`` writes undone.

    The wizard quotes and backslash-escapes every value so the file survives
    both ``docker compose`` and a shell that sources it; this is the other half
    of that round trip. A line that is not a pair is skipped rather than
    raising: this file is read on the path whose whole job is diagnosing a
    broken box.
    """
    values: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        name, _, value = line.partition("=")
        name = name.strip()
        if name.startswith("export "):
            name = name[len("export ") :].strip()
        if not name:
            continue
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
            quote = value[0]
            value = value[1:-1]
            if quote == '"':
                # Only double quotes carry escapes, which is what the writer
                # emits and what docker compose itself undoes.
                value = value.replace('\\"', '"').replace("\\\\", "\\")
        values[name] = value
    return values


def instance_env_path(workspace: Path | str) -> Path:
    """Where this instance keeps its env file."""
    return Path(workspace).expanduser() / INSTANCE_ENV_FILENAME


def load_instance_env(
    workspace: Path | str,
    *,
    environ: MutableMapping[str, str] | None = None,
) -> EnvFileLoad:
    """Load ``<workspace>/genus.env`` into ``environ``. Never raises.

    Returns what happened, including the sentence to print when the file was
    refused. Absent is not a failure — every substrate but compose has no such
    file, and this is called unconditionally.
    """
    import os

    target = environ if environ is not None else os.environ
    path = instance_env_path(workspace)

    if path.is_symlink():
        return EnvFileLoad(
            path=path,
            present=True,
            refused=(
                f"{path} is a symlink; refusing to read this instance's credentials "
                "through one. Replace it with the file itself."
            ),
        )
    try:
        info = path.stat()
    except OSError:
        return EnvFileLoad(path=path)
    if not stat.S_ISREG(info.st_mode):
        return EnvFileLoad(path=path, present=True, refused=f"{path} is not a regular file")

    mode = stat.S_IMODE(info.st_mode)
    if mode != REQUIRED_MODE:
        return EnvFileLoad(
            path=path,
            present=True,
            refused=(
                f"{path} is mode {mode:o}, so other accounts on this machine can read "
                f"this instance's database password and provider key. It was NOT loaded: "
                f"chmod 600 {path}"
            ),
        )

    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        return EnvFileLoad(path=path, present=True, refused=f"{path} could not be read: {exc}")

    added: list[str] = []
    for name, value in parse_env_file(text).items():
        if target.get(name):
            continue
        target[name] = value
        added.append(name)
    return EnvFileLoad(path=path, present=True, names=tuple(added))
