"""``<workspace>/genus.env`` is the one copy of a compose instance's secrets.

The containers read it through ``env_file``. The HOST needs it too, and that is
what this module is for: ``genus doctor`` and the wizard's ``verify`` step both
resolve the database connection from the process environment, and on a compose
install the password was GENERATED by ``genus init`` and deliberately stored
nowhere else — so without this, the doctor reports ``db.connect`` failing
against a database that is running perfectly well, and the wizard's own last
step fails the install it just completed.

Two rules, and the second is why this is not three lines of ``dotenv``:

**The file must be 0600.** It carries the database password and the provider
key. A file the group or the world can read is refused, loudly, rather than
loaded — a credential file whose permissions slipped is a finding, and reading
it anyway would hide it forever.

**An exported value always wins.** The load is ``setdefault``: an operator who
exported ``ROBOTHOR_DB_PASSWORD`` before running the command means it.
"""

from __future__ import annotations

from pathlib import Path  # noqa: TC003 - used as a runtime argument type here

import pytest

from robothor.secrets.env_file import (
    INSTANCE_ENV_FILENAME,
    REQUIRED_MODE,
    load_instance_env,
    parse_env_file,
)

BODY = """# Written by `genus init --substrate compose`.
GENUS_IMAGE_TAG="v1.70.0"
ROBOTHOR_DB_PASSWORD="two words \\"quoted\\""

# The provider credential.
OPENROUTER_API_KEY="sk-not-a-real-key"
"""


def _write(workspace: Path, body: str = BODY, *, mode: int = REQUIRED_MODE) -> Path:
    workspace.mkdir(parents=True, exist_ok=True)
    path = workspace / INSTANCE_ENV_FILENAME
    path.write_text(body, encoding="utf-8")
    path.chmod(mode)
    return path


class TestParsing:
    def test_it_unquotes_and_unescapes_what_the_wizard_wrote(self):
        parsed = parse_env_file(BODY)

        assert parsed["GENUS_IMAGE_TAG"] == "v1.70.0"
        # The round trip that matters: `genus init` quotes and escapes so the
        # file survives both docker compose and a shell.
        assert parsed["ROBOTHOR_DB_PASSWORD"] == 'two words "quoted"'
        assert parsed["OPENROUTER_API_KEY"] == "sk-not-a-real-key"

    def test_comments_blanks_and_junk_lines_are_not_values(self):
        parsed = parse_env_file("# a comment\n\nNOT_A_PAIR\nA=1\n")

        assert parsed == {"A": "1"}

    def test_an_export_prefix_is_tolerated(self):
        # `set -a; . ./genus.env` was the documented workaround this replaces,
        # and a file an operator hand-edited may carry its habits.
        assert parse_env_file("export A=1\n") == {"A": "1"}


class TestLoading:
    def test_it_fills_the_environment_from_the_workspace_file(self, tmp_path):
        _write(tmp_path)
        environ: dict[str, str] = {}

        result = load_instance_env(tmp_path, environ=environ)

        assert result.loaded
        assert environ["ROBOTHOR_DB_PASSWORD"] == 'two words "quoted"'
        assert "ROBOTHOR_DB_PASSWORD" in result.names

    def test_an_exported_value_wins(self, tmp_path):
        _write(tmp_path)
        environ = {"ROBOTHOR_DB_PASSWORD": "what the operator exported"}

        result = load_instance_env(tmp_path, environ=environ)

        assert environ["ROBOTHOR_DB_PASSWORD"] == "what the operator exported"
        assert "ROBOTHOR_DB_PASSWORD" not in result.names

    def test_no_file_is_not_a_failure(self, tmp_path):
        result = load_instance_env(tmp_path, environ={})

        assert not result.present
        assert not result.refused
        assert not result.loaded

    @pytest.mark.parametrize("mode", [0o644, 0o640, 0o660, 0o604])
    def test_a_readable_file_is_refused_by_name_and_not_loaded(self, tmp_path, mode):
        path = _write(tmp_path, mode=mode)
        environ: dict[str, str] = {}

        result = load_instance_env(tmp_path, environ=environ)

        assert environ == {}, "a group- or world-readable credential file was read anyway"
        assert str(path) in result.refused
        assert "chmod 600" in result.refused
        assert f"{mode:o}" in result.refused

    def test_a_symlink_is_refused(self, tmp_path):
        real = _write(tmp_path / "elsewhere")
        workspace = tmp_path / "instance"
        workspace.mkdir()
        (workspace / INSTANCE_ENV_FILENAME).symlink_to(real)

        result = load_instance_env(workspace, environ={})

        assert "symlink" in result.refused.lower()
        assert not result.loaded

    def test_it_defaults_to_the_real_environment(self, tmp_path, monkeypatch):
        _write(tmp_path, 'A_TEST_ONLY_NAME="set-from-the-file"\n')
        monkeypatch.delenv("A_TEST_ONLY_NAME", raising=False)

        load_instance_env(tmp_path)

        import os

        assert os.environ["A_TEST_ONLY_NAME"] == "set-from-the-file"
