{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "genus-os.fullname" . }}-credentials
  labels:
    {{- include "genus-os.labels" (dict "root" . "component" "shared") | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "genus-os.fullname" . }}-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    {{- range .Values.externalSecrets.keys }}
    - secretKey: {{ .envVar }}
      remoteRef:
        key: {{ $.Values.externalSecrets.remoteRef }}
        property: {{ .vaultKey }}
    {{- end }}
{{- end }}
